### ISSUE TITLE
Let user decide if a "bug" should be a "hotfix" or a "feature"

### ISSUE THREAD

**Issue by k-bx** [donaldpiret/github-pivotal-flow#7]
In my systems, most tickets of a type "bug" would be fixed in next release cycle and released at the end of a sprint.

And only super-severe-bugs, which broke production drastically, would go as a git-flow's "hotfix", which is based on top of master.

Currently, github-pivotal-flow would recognize a pivotal's "bug" as a git-flow's "hotfix", so it would create a hotfix/blablabla branch that would be based on top of master. I think it shouldn't be this way, but rather user should be asked if this bug is a hotfix or a feature.

Thank you!

**Comment by k-bx** [comment]
After some investigation I see that this was actually intended behavior:

https://github.com/donaldpiret/github-pivotal-flow/blob/master/lib/github_pivotal_flow/story.rb#L277

E.g. a tag "hotfix" is recognized in a special way and hotfix on top of master is created. Would be cool to print this into output (e.g. "found a tag hotfix, making a hotfix-branch on top of master").

Closing for now.

**Comment by donaldpiret** [comment]
Hey, thanks for the feedback. Really appreciate it. Will try to implement your suggestions and have a look at your pull request over the weekend :+1:

**Comment by k-bx** [comment]
Thanks for a very awesome tool, saves time a lot!
